### ISSUE TITLE
Current terraformer interferes with demeter CTD

### ISSUE THREAD

**Issue by Linguardium** [SuperCoder7979/vanillaplusbiomes#1]
the version of terraformer you included also has a new cropblock mixin that cannot be applied with demeter also installed.
this causes a ctd.

https://paste.dimdev.org/ozonazijev.cpp

**Comment by jaskarth** [comment]
Check the 0.1.3 release on curseforge and see if that fixes the issue please.

**Comment by Linguardium** [comment]
seems to work :)

**Comment by Linguardium** [comment]
fixed by commit bfa1384

**Comment by jaskarth** [comment]
cool! glad it worked
