### ISSUE TITLE
Ancient Dark Oak Forest Spawns Without Trees

### ISSUE THREAD

**Issue by CosmicParticl** [SuperCoder7979/vanillaplusbiomes#10]
No trees generate in the Ancient Dark Forest biome, despite what the name implies.
![2021-06-17_16 23 11](https://user-images.githubusercontent.com/54153712/122467370-6d3abd00-cf88-11eb-9884-13c614f5337c.png)

**Comment by jaskarth** [comment]
Fixed in 0.3.2. Thanks for the report!

**Comment by CosmicParticl** [comment]
I updated to the latest version and Ancient Dark Oak forests now spawn correctly, but in vanilla dark oak biomes I see this:
![2021-06-17_19 16 41](https://user-images.githubusercontent.com/54153712/122483511-c3b3f580-cfa0-11eb-9f9a-911bc44bc600.png)
Do you think this is caused by this mod?

**Comment by jaskarth** [comment]
Shouldn't be. They work fine for me.
